{% set name = "csubst" %}
{% set version = "1.4.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/kamome1201/csubst/archive/refs/tags/v{{ version }}.tar.gz
  sha256: "TO_BE_REPLACED"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8

test:
  imports:
    - csubst

about:
  home: "https://github.com/kfuku52/csubst"
  license: "BSD-3-Clause"
  license_file: "LICENSE"
  summary: "CSUBST () is a tool for analyzing Combinatorial SUBSTitutions of codon sequences in phylogenetic trees."
